"""
backend/agents/reporting.py
────────────────────────────
Reporting Agent — Phase 4

Responsibilities:
1. Assemble a Google Model Card (markdown + HTML) from the final PipelineState.
2. Render the full audit trail as a chronological HTML timeline.
3. Set state.final_recommendation (DEPLOY / NO_DEPLOY / CONDITIONAL).
4. Write output files and update state with their paths.

Model Card sections (Google Model Card format):
  - Model Details (name, family, hyperparameters)
  - Intended Use
  - Factors (protected attributes, domain)
  - Performance Metrics (AUC, F1, calibration)
  - Ethical Considerations
  - Fairness Results
  - Caveats and Recommendations
  - Deploy / No-Deploy recommendation with reasoning
"""

from __future__ import annotations

import os
from datetime import datetime
from typing import Any

from jinja2 import Environment, BaseLoader

from backend.state.schema import (
    AuditStatus,
    DeployRecommendation,
    PipelineState,
)
from backend.state.store import log_step_and_broadcast_sync

_OUTPUT_DIR = os.getenv("REPORTS_OUTPUT_DIR", "./artifacts/reports/")

# ---------------------------------------------------------------------------
# Model Card Jinja2 template
# ---------------------------------------------------------------------------

_MODEL_CARD_TEMPLATE = """
<div align="center">
  <h1>Model Card: {{ model_name }}</h1>
  <p><em>Generated by Sentinel-ML Autonomous Pipeline</em></p>
</div>

<hr />

## 📋 Overview
- **Run ID:** `{{ run_id }}`
- **Generated:** {{ generated_at }}
- **Domain:** <span style="background:#e0e7ff; color:#3730a3; padding: 2px 6px; border-radius:4px;">{{ domain }}</span>
- **Task Type:** <span style="background:#dcfce7; color:#166534; padding: 2px 6px; border-radius:4px;">{{ task_type }}</span>

### Intended Use
> {{ objective }}

---

## 🔬 Model Details
- **Model Family:** {{ model_family }}
- **Target Column:** `{{ target_column }}`
- **Optimization Priority:** {{ optimization_priority }}

<details>
<summary><strong>View Hyperparameters</strong></summary>
<ul>
{% for k, v in hyperparameters.items() %}
<li><code>{{ k }}</code>: {{ v }}</li>
{% endfor %}
</ul>
</details>

---

## 📊 Data Profile & Engineering
- **Training Data:** {{ n_rows }} rows × {{ n_cols }} columns
- **Class Balancing (SMOTE):** {% if smote_applied %}✅ Applied{% else %}❌ Not Applied{% endif %}
- **Feature Optimization:** {{ feature_optimization }}
- **Outlier Removal:** {{ outlier_removal }}
- **Numeric Scaling:** {{ numeric_scaler }}

---

## 🎯 Performance Metrics
| Metric | Value |
|--------|-------|
| **AUC-ROC** | `{{ auc_roc }}` |
| **F1 Score** | `{{ f1_score }}` |
| **Precision** | `{{ precision }}` |
| **Recall** | `{{ recall }}` |
| **Accuracy** | `{{ accuracy }}` |

---

## ⚖️ Governance & Fairness
- **Protected Attributes:** {{ protected_attrs }}
- **Regulations:** {{ regulations | join(", ") }}

### Fairness Audits
| Metric | Value | Threshold | Status |
|--------|-------|-----------|--------|
| Disparate Impact ({{ protected_attr }}) | `{{ disparate_impact }}` | ≥ {{ di_threshold }} | **{{ fairness_status }}** |
| Equal Opportunity Difference | `{{ eod }}` | ≤ {{ eod_threshold }} | **{{ fairness_status }}** |

### Robustness & Stability
- **Robustness (Covariate Shift):** AUC degradation = `{{ auc_degradation }}%` → **{{ robustness_status }}**
- **Stability (Bootstrap Variance):** `{{ bootstrap_variance }}` → **{{ stability_status }}**

**Governance loops required:** {{ iteration_count }}
**Overall Audit Status:** {% if overall_status == 'PASS' %}✅ PASS{% else %}❌ {{ overall_status }}{% endif %}

{% if failure_reasons %}
**Failure reasons addressed in redesign loops:**
{% for reason in failure_reasons %}- {{ reason }}
{% endfor %}
{% endif %}

---

## 🧠 Explainability
**Top contributing features (SHAP):**
{% for feat in top_features %}
- 🟢 `{{ feat }}`
{% endfor %}

---

## 🚨 Ethical Considerations
- Model trained and evaluated with explicit fairness constraints.
- Human-in-the-loop checkpoints were applied at every stage transition.
- All decisions are logged in the immutable audit trail.
- Model should not be used for decisions beyond its declared intended use.

---

## 🚀 Final Recommendation

<div style="background-color: {% if recommendation == 'DEPLOY' %}#dcfce7{% else %}#fee2e2{% endif %}; padding: 15px; border-radius: 8px; border-left: 5px solid {% if recommendation == 'DEPLOY' %}#22c55e{% else %}#ef4444{% endif %};">
  <h3 style="margin-top: 0;">{{ recommendation }}</h3>
  <p style="margin-bottom: 0;"><strong>Reasoning:</strong> {{ recommendation_reasoning }}</p>
</div>
"""

_AUDIT_TRAIL_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Sentinel-ML Audit Trail — Run {{ run_id }}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0f172a; color: #e2e8f0; margin: 0; padding: 2rem; }
  h1 { color: #818cf8; font-size: 1.8rem; margin-bottom: 0.5rem; }
  .subtitle { color: #64748b; margin-bottom: 2rem; font-size: 0.9rem; }
  .timeline { position: relative; padding-left: 2rem; }
  .timeline::before { content: ''; position: absolute; left: 0.65rem; top: 0; bottom: 0; width: 2px; background: #334155; }
  .entry { position: relative; margin-bottom: 2rem; background: #1e293b; border-radius: 12px; padding: 1.25rem 1.5rem; border: 1px solid #334155; }
  .entry::before { content: ''; position: absolute; left: -1.85rem; top: 1.5rem; width: 12px; height: 12px; border-radius: 50%; background: #6366f1; border: 2px solid #0f172a; }
  .entry-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.75rem; }
  .stage-badge { background: #312e81; color: #a5b4fc; padding: 0.2rem 0.75rem; border-radius: 20px; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; }
  .user-badge { padding: 0.2rem 0.75rem; border-radius: 20px; font-size: 0.75rem; font-weight: 600; }
  .approved { background: #052e16; color: #4ade80; }
  .rejected { background: #450a0a; color: #f87171; }
  .counter_propose { background: #1c1917; color: #fb923c; }
  .pending { background: #1e3a5f; color: #60a5fa; }
  .timestamp { color: #64748b; font-size: 0.8rem; }
  .proposed-action { font-weight: 600; color: #f1f5f9; margin-bottom: 0.5rem; }
  .reasoning { color: #94a3b8; font-size: 0.875rem; line-height: 1.6; }
  .user-note { margin-top: 0.75rem; padding: 0.5rem 0.75rem; background: #0f172a; border-left: 3px solid #6366f1; border-radius: 4px; font-size: 0.85rem; color: #cbd5e1; }
</style>
</head>
<body>
<h1>🛡️ Sentinel-ML Audit Trail</h1>
<p class="subtitle">Run ID: {{ run_id }} | Generated: {{ generated_at }}</p>
<div class="timeline">
{% for entry in entries %}
<div class="entry">
  <div class="entry-header">
    <span class="stage-badge">{{ entry.stage }}</span>
    <div style="display:flex;gap:0.5rem;align-items:center">
      <span class="user-badge {{ entry.user_action }}">{{ entry.user_action | upper }}</span>
      <span class="timestamp">{{ entry.timestamp }}</span>
    </div>
  </div>
  <div class="proposed-action">{{ entry.proposed_action }}</div>
  <div class="reasoning">{{ entry.reasoning }}</div>
  {% if entry.user_note %}
  <div class="user-note"><strong>User note:</strong> {{ entry.user_note }}</div>
  {% endif %}
  {% if entry.agent_justification %}
  <div class="user-note"><strong>Agent justification:</strong> {{ entry.agent_justification }}</div>
  {% endif %}
</div>
{% endfor %}
</div>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------


def run_reporting(state: PipelineState) -> PipelineState:
    """
    Assemble Model Card + Audit Trail. Set final_recommendation.
    """
    os.makedirs(_OUTPUT_DIR, exist_ok=True)

    # Determine final recommendation
    state.final_recommendation, reasoning = _compute_recommendation(state)
    state.final_recommendation_reasoning = reasoning

    log_step_and_broadcast_sync(state, "reporting", "Reporting Started", "Compiling metrics, schemas, and governance audits into final Model Card.")

    # Generate Model Card
    card_md = _render_model_card(state)
    card_path = os.path.join(_OUTPUT_DIR, f"{state.run_id}_model_card.md")
    with open(card_path, "w", encoding="utf-8") as f:
        f.write(card_md)
    state.model_card_path = card_path

    # Generate Audit Trail HTML
    audit_html = _render_audit_trail(state)
    audit_path = os.path.join(_OUTPUT_DIR, f"{state.run_id}_audit_trail.html")
    with open(audit_path, "w", encoding="utf-8") as f:
        f.write(audit_html)
    state.audit_trail_path = audit_path
    
    log_step_and_broadcast_sync(state, "reporting", "Reporting Complete", f"Generated Model Card and Audit Trail. Final Recommendation: {state.final_recommendation}")

    return state


# ---------------------------------------------------------------------------
# Recommendation logic
# ---------------------------------------------------------------------------


def _compute_recommendation(state: PipelineState):
    audit = state.governance_audit
    if audit.overall_status in (AuditStatus.PASS, "PASS"):
        return DeployRecommendation.DEPLOY, (
            "All governance audits passed (fairness, robustness, stability). "
            f"Model meets {', '.join(audit.compliance_checklist[:3] or ['internal'])} requirements. "
            "Human sign-off recommended before production deployment."
        )
    elif audit.overall_status in (AuditStatus.FAIL, "FAIL"):
        return DeployRecommendation.NO_DEPLOY, (
            "Governance audit failed after "
            f"{audit.iteration_count} redesign loop(s). "
            "Remaining issues: " + "; ".join(audit.failure_reasons[:2]) + ". "
            "Do not deploy until issues are resolved."
        )
    else:
        return DeployRecommendation.CONDITIONAL, (
            "Governance audit was skipped or partially completed. "
            "Manual review required before deployment."
        )


# ---------------------------------------------------------------------------
# Template rendering
# ---------------------------------------------------------------------------


def _render_model_card(state: PipelineState) -> str:
    env = Environment(loader=BaseLoader())
    template = env.from_string(_MODEL_CARD_TEMPLATE)

    best_model = next((m for m in state.model_leaderboard if m.is_selected), None)
    audit = state.governance_audit
    fairness = audit.fairness

    return template.render(
        run_id=state.run_id,
        generated_at=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        domain=state.objective.domain_tag,
        model_name=state.selected_model_name or "N/A",
        model_family=best_model.model_family if best_model else "N/A",
        task_type=state.objective.task_type,
        target_column=state.objective.target_column or "N/A",
        optimization_priority=state.objective.optimization_priority or "maximize AUC",
        hyperparameters=best_model.hyperparameters if best_model else {},
        objective=state.objective.raw_text,
        protected_attrs=", ".join(state.objective.protected_attributes) or "None declared",
        regulations=audit.compliance_checklist or ["generic"],
        requires_explainability=True,
        auc_roc=best_model.auc_roc if best_model else "N/A",
        f1_score=best_model.f1_score if best_model else "N/A",
        precision=best_model.precision if best_model else "N/A",
        recall=best_model.recall if best_model else "N/A",
        accuracy=best_model.accuracy if best_model else "N/A",
        protected_attr=fairness.protected_attribute or "N/A",
        disparate_impact=fairness.disparate_impact,
        di_threshold=audit.compliance_thresholds.get("disparate_impact_min", 0.80),
        eod=fairness.equal_opportunity_difference,
        eod_threshold=audit.compliance_thresholds.get("equal_opportunity_diff_max", 0.10),
        fairness_status=fairness.status,
        auc_degradation=audit.robustness.auc_degradation_pct,
        robustness_status=audit.robustness.status,
        bootstrap_variance=audit.stability.metric_variance,
        stability_status=audit.stability.status,
        overall_status=audit.overall_status,
        failure_reasons=audit.failure_reasons,
        iteration_count=audit.iteration_count,
        top_features=state.explainability.top_features_summary[:5] or ["N/A"],
        recommendation=state.final_recommendation,
        recommendation_reasoning=state.final_recommendation_reasoning or "",
        n_rows=state.data_health_report.row_count if getattr(state, "data_health_report") else "N/A",
        n_cols=state.data_health_report.column_count if getattr(state, "data_health_report") else "N/A",
        smote_applied=getattr(state, "smote_applied", False),
        feature_optimization=getattr(state.objective, "feature_optimization", "None"),
        outlier_removal=getattr(state.objective, "outlier_removal", "None"),
        numeric_scaler=getattr(state.objective, "numeric_scaler", "StandardScaler"),
    )


def _render_audit_trail(state: PipelineState) -> str:
    env = Environment(loader=BaseLoader())
    template = env.from_string(_AUDIT_TRAIL_TEMPLATE)

    entries = [
        {
            "stage": entry.stage,
            "proposed_action": entry.proposed_action,
            "reasoning": entry.reasoning,
            "user_action": entry.user_action if isinstance(entry.user_action, str) else entry.user_action.value,
            "user_note": entry.user_note,
            "agent_justification": entry.agent_justification,
            "timestamp": entry.timestamp.strftime("%Y-%m-%d %H:%M:%S UTC"),
        }
        for entry in state.decisions_log
    ]

    return template.render(
        run_id=state.run_id,
        generated_at=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        entries=entries,
    )
